# Generated by Django 6.0.6 on 2026-06-16 02:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='nombre')),
                ('asset_type', models.CharField(choices=[('server', 'Servidor'), ('application', 'Aplicación'), ('database', 'Base de datos'), ('network', 'Red'), ('data', 'Datos / Información'), ('endpoint', 'Endpoint'), ('other', 'Otro')], default='other', max_length=20, verbose_name='tipo')),
                ('criticality', models.CharField(choices=[('low', 'Baja'), ('medium', 'Media'), ('high', 'Alta'), ('critical', 'Crítica')], default='medium', max_length=10, verbose_name='criticidad')),
                ('owner', models.CharField(blank=True, max_length=120, verbose_name='responsable')),
                ('description', models.TextField(blank=True, verbose_name='descripción')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'activo',
                'verbose_name_plural': 'activos',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Control',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, verbose_name='código')),
                ('title', models.CharField(max_length=255, verbose_name='título')),
                ('domain', models.CharField(blank=True, max_length=120, verbose_name='dominio')),
                ('description', models.TextField(blank=True, verbose_name='descripción')),
            ],
            options={
                'verbose_name': 'control',
                'verbose_name_plural': 'controles',
                'ordering': ['framework', 'code'],
            },
        ),
        migrations.CreateModel(
            name='ControlAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_implemented', 'No implementado'), ('partial', 'Parcial'), ('implemented', 'Implementado'), ('not_applicable', 'No aplica')], default='not_implemented', max_length=20, verbose_name='estado')),
                ('notes', models.TextField(blank=True, verbose_name='notas')),
                ('evidence', models.FileField(blank=True, null=True, upload_to='evidence/', verbose_name='evidencia')),
                ('assessed_at', models.DateTimeField(auto_now=True, verbose_name='fecha de evaluación')),
                ('assessed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessments', to=settings.AUTH_USER_MODEL)),
                ('control', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='compliance.control')),
            ],
            options={
                'verbose_name': 'evaluación de control',
                'verbose_name_plural': 'evaluaciones de control',
                'ordering': ['-assessed_at'],
            },
        ),
        migrations.CreateModel(
            name='Framework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='nombre')),
                ('version', models.CharField(blank=True, max_length=40, verbose_name='versión')),
                ('description', models.TextField(blank=True, verbose_name='descripción')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'marco',
                'verbose_name_plural': 'marcos',
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('name', 'version'), name='unique_framework_version')],
            },
        ),
        migrations.AddField(
            model_name='control',
            name='framework',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='controls', to='compliance.framework'),
        ),
        migrations.CreateModel(
            name='Risk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='título')),
                ('description', models.TextField(blank=True, verbose_name='descripción')),
                ('likelihood', models.IntegerField(choices=[(1, 'Muy bajo'), (2, 'Bajo'), (3, 'Medio'), (4, 'Alto'), (5, 'Muy alto')], verbose_name='probabilidad')),
                ('impact', models.IntegerField(choices=[(1, 'Muy bajo'), (2, 'Bajo'), (3, 'Medio'), (4, 'Alto'), (5, 'Muy alto')], verbose_name='impacto')),
                ('status', models.CharField(choices=[('open', 'Abierto'), ('mitigating', 'En mitigación'), ('accepted', 'Aceptado'), ('closed', 'Cerrado')], default='open', max_length=12, verbose_name='estado')),
                ('treatment', models.TextField(blank=True, verbose_name='plan de tratamiento')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='risks', to='compliance.asset')),
            ],
            options={
                'verbose_name': 'riesgo',
                'verbose_name_plural': 'riesgos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='control',
            constraint=models.UniqueConstraint(fields=('framework', 'code'), name='unique_control_per_framework'),
        ),
    ]
